### ISSUE TITLE
GUILD_TEST

### ISSUE THREAD

**Issue by MrVyM** [AzerX2/ImproseToi#11]
https://github.com/AzerX2/ImproseToi/blob/87620a168a17dc6437900c422b282f9bb70c6e02/services/discord/Event/ready.js#L13

Ca, c'est typiquement un truc que l'on met dans le .env

**Comment by AzerX2** [comment]
je trouve pas ça méga utile mais allez

**Comment by MrVyM** [comment]
c'est juste que si tu veux un code clean, tu n'as aucune valeur harcoder dans le code
