### ISSUE TITLE
Vous avez dit "Evolutivité"

### ISSUE THREAD

**Issue by MrVyM** [AzerX2/ImproseToi#2]
https://github.com/AzerX2/ImproseToi/blob/0804225a944058c3c23ec6a890b7f8bed368ba1a/controllers/presenceController.js#L16-L25
![image](https://github.com/AzerX2/ImproseToi/assets/81855526/883af851-7413-4aea-829c-a99119a57f90)
oui oui baguette

**Comment by AzerX2** [comment]
good
