### ISSUE TITLE
Default Date Model

### ISSUE THREAD

**Issue by MrVyM** [AzerX2/ImproseToi#4]
https://github.com/AzerX2/ImproseToi/blob/0804225a944058c3c23ec6a890b7f8bed368ba1a/models/eloquenceModel.js#L4

Euh.. Pourquoi tu mets un Date.now() ?
Et normalement, si ton archi est bonne, elle peut pas etre null

**Comment by AzerX2** [comment]
parce que comme ça pas besoin de faire un cas précis pour la création du bilan

**Comment by MrVyM** [comment]
fair
