### ISSUE TITLE
Et bah ouais, c'est dommage pour toi

### ISSUE THREAD

**Issue by MrVyM** [AzerX2/ImproseToi#6]
https://github.com/AzerX2/ImproseToi/blob/87620a168a17dc6437900c422b282f9bb70c6e02/controllers/desinscriptionController.js#L20

Tu peux pas juste dire a ton user qu'il ne peut pas se desinscrire et rien faire. Au pire, met un contact pour se desinscrire

**Comment by AzerX2** [comment]
bonne idée

**Comment by AzerX2** [comment]
c'est good
