### ISSUE TITLE
Wait why write

### ISSUE THREAD

**Issue by MrVyM** [AzerX2/ImproseToi#7]
https://github.com/AzerX2/ImproseToi/blob/87620a168a17dc6437900c422b282f9bb70c6e02/services/discord/SlashCommandes/bilan.js#L47

Donc la si je comprends bien, tu ne peux avoir qu'un seul atelier a la fois, car tu a hard code le nom du fichier.
Maybe rajouter la date (M/J/H - hh:mm) dans le nom du fichier et dev une cron tab pour degager les anciens files

**Comment by AzerX2** [comment]
je le supprime juste après donc pas besoin
